import {
  ArrowRight, CheckCircle, Code2, ExternalLink, Github,
  Linkedin, Mail, Play, ShieldCheck, Sparkles,
} from "lucide-react";

// ─── Data ────────────────────────────────────────────────────────────────────

const LINKS = {
  email:       "mailto:sameershaik200016@gmail.com",
  linkedin:    "https://www.linkedin.com/in/iamsameershaik/",
  portfolio:   "https://iamsameershaik.netlify.app/",
  github:      "https://github.com/iamsameershaik/legal-queue-copilot",
  walkthrough: "https://drive.google.com/file/d/1glA6a2GmQRi32N1jdMaqJXCDnUl7dNwb/view",
};

const TIMELINE = [
  {
    tag: "v1 · Sprint",
    title: "PortSwigger AI Pioneer take-home",
    desc: "One-week sprint to prototype AI-assisted first-pass legal triage. Delivered a working review engine, playbook with 10 rules, Green/Amber/Red routing, human decision controls, and eval dashboard.",
  },
  {
    tag: "v2 · UI",
    title: "Premium command-centre interface",
    desc: "Full visual redesign. Deep green/black design token system, stat cards, risk badge system, collapsible sidebar, and mobile-responsive layout.",
  },
  {
    tag: "v2 · Guardrails",
    title: "Contract Intake Guardrail",
    desc: "Deterministic preflight classifier that accepts, warns, or rejects input before entering the review queue. Fixture-based eval covers all paths.",
  },
  {
    tag: "v2 · Evidence",
    title: "Evidence & Authority Layer",
    desc: "Every finding and redline carries structured citations: contract excerpt, playbook rule, provenance metadata, legal-reference status, and authority status. Citation coverage verifier runs automatically.",
  },
  {
    tag: "v2 · Governance",
    title: "Handover Lab",
    desc: "Governance-focused readiness cockpit: dual readiness scores, control coverage, production blockers, governance matrix, adoption plan, and scope governance note.",
  },
];

const DECISIONS = [
  {
    icon: <Code2 size={14} color="#16C784" />,
    title: "Deterministic engine first",
    desc: "A regex-signal review engine produces reliable, inspectable, and safe demo output without API keys. LLM integration is architected as the next layer, not a prerequisite.",
  },
  {
    icon: <ShieldCheck size={14} color="#16C784" />,
    title: "Guardrails before generation",
    desc: "Input quality gates run before any review. Garbage in, garbage out is a real legal risk — the preflight classifier prevents low-quality input from reaching the review engine.",
  },
  {
    icon: <CheckCircle size={14} color="#16C784" />,
    title: "Evidence before authority",
    desc: "Every output cites the contract text and playbook rule that triggered it. External legal authority is structurally supported but deliberately left uncurated — fabricated legal references are treated as a critical failure mode.",
  },
  {
    icon: <ArrowRight size={14} color="#16C784" />,
    title: "Human approval by design",
    desc: "Accept / Edit / Reject / Escalate controls are mandatory, not optional. The system explicitly blocks sending redlines without review. This is the product's core safety invariant.",
  },
  {
    icon: <Sparkles size={14} color="#16C784" />,
    title: "Eval coverage as product feature",
    desc: "Citation coverage verification and preflight fixture tests are first-class features, not dev tooling. Governance stakeholders can inspect pass rates directly in the Handover Lab.",
  },
];

const METRICS = [
  { label: "Preflight guardrail fixtures", value: "18/18", note: "100% pass rate · 18 synthetic cases" },
  { label: "Citation coverage",            value: "100%",  note: "128/128 checks · 5 sample contracts" },
  { label: "Fabricated legal references",  value: "0",     note: "Zero external URLs generated by engine" },
  { label: "Human approval required",      value: "Always",note: "Before any external redline is sent" },
];

// ─── Sub-components ──────────────────────────────────────────────────────────

function CTAButton({
  href, icon, label, primary = false,
}: { href: string; icon: React.ReactNode; label: string; primary?: boolean }) {
  return (
    <a
      href={href}
      target="_blank"
      rel="noreferrer"
      className={primary ? "btn-primary" : "btn-secondary"}
      style={{ textDecoration: "none", display: "inline-flex", alignItems: "center", gap: 6 }}
    >
      {icon}
      {label}
    </a>
  );
}

function SectionHeader({ title }: { title: string }) {
  return (
    <h2 className="section-title mb-4">{title}</h2>
  );
}

// ─── Page ────────────────────────────────────────────────────────────────────

export default function BuilderNotes() {
  return (
    <div className="w-full px-4 sm:px-6 lg:px-8 py-8">

      {/* Page header */}
      <div className="mb-6">
        <h1 className="page-title mb-1">Builder Notes</h1>
        <p className="body-text">Case study, product decisions, and builder context.</p>
      </div>

      {/* ── Hero card ───────────────────────────────────────────────────── */}
      <div
        className="relative overflow-hidden rounded-2xl p-6 sm:p-8 mb-6"
        style={{
          background: "linear-gradient(135deg, #0B2B26 0%, #051F20 60%, #031314 100%)",
          border: "1px solid rgba(22,199,132,0.22)",
          boxShadow: "0 0 60px rgba(22,199,132,0.06), 0 2px 24px rgba(3,19,20,0.6)",
        }}
      >
        {/* Background glow */}
        <div
          aria-hidden="true"
          style={{
            position: "absolute",
            top: -60,
            right: -40,
            width: 320,
            height: 320,
            borderRadius: "50%",
            background: "radial-gradient(circle, rgba(22,199,132,0.10) 0%, transparent 70%)",
            pointerEvents: "none",
          }}
        />

        <div className="relative z-10 flex flex-col lg:flex-row lg:items-start lg:justify-between gap-8">
          {/* Left: identity */}
          <div className="flex-1 min-w-0">
            <p
              className="text-[11px] font-semibold tracking-widest uppercase mb-3"
              style={{ color: "#16C784", letterSpacing: "0.12em" }}
            >
              Built by Sameer Shaik
            </p>

            <h2
              className="font-bold leading-none mb-3"
              style={{ fontSize: "clamp(32px, 5vw, 52px)", color: "#F2FFF7", letterSpacing: "-0.02em" }}
            >
              ClauseCompass v2
            </h2>

            <p
              className="text-[15px] font-medium mb-4 max-w-[520px] leading-relaxed"
              style={{ color: "#8EB69B" }}
            >
              AI-assisted first-pass legal triage, built as a human-in-the-loop workflow for routine commercial contracts.
            </p>

            <p
              className="text-[13px] mb-1 font-medium"
              style={{ color: "var(--cc-text-soft)" }}
            >
              Sameer Shaik &middot; AI Solutions Engineer
            </p>

            <p
              className="text-[13px] font-semibold mb-5"
              style={{ color: "#16C784" }}
            >
              I build AI workflows that stay useful when trust, uncertainty, and human approval matter.
            </p>

            <p
              className="text-[12px] leading-relaxed mb-6 max-w-[520px]"
              style={{ color: "#566B76" }}
            >
              ClauseCompass began as a PortSwigger AI Pioneer take-home prototype and was extended
              into a portfolio-grade legal triage workflow with intake guardrails, evidence-grounded
              findings, citation coverage verification, and governance handover controls.
            </p>

            {/* CTA row */}
            <div className="flex flex-wrap gap-2">
              <CTAButton href={LINKS.walkthrough} icon={<Play size={13} />} label="Watch walkthrough" primary />
              <CTAButton href={LINKS.email}       icon={<Mail size={13} />}     label="Email"     />
              <CTAButton href={LINKS.linkedin}    icon={<Linkedin size={13} />} label="LinkedIn"  />
              <CTAButton href={LINKS.portfolio}   icon={<ExternalLink size={13} />} label="Portfolio" />
              <CTAButton href={LINKS.github}      icon={<Github size={13} />}   label="GitHub"    />
            </div>

            <p className="text-[10px] mt-3" style={{ color: "#364F5A" }}>
              Original v1 walkthrough — the live app has since been extended into ClauseCompass v2.
            </p>
          </div>

          {/* Right: quick-stats column */}
          <div className="flex-shrink-0 flex flex-col gap-3 min-w-[180px]">
            {[
              { label: "Phases shipped",    value: "6" },
              { label: "Playbook rules",    value: "10" },
              { label: "Guardrail fixtures",value: "18" },
              { label: "Citation checks",   value: "128" },
            ].map(({ label, value }) => (
              <div
                key={label}
                className="rounded-xl px-4 py-3 text-center"
                style={{
                  background: "rgba(11,43,38,0.6)",
                  border: "1px solid rgba(22,199,132,0.12)",
                }}
              >
                <p
                  className="text-[22px] font-bold leading-none mb-0.5"
                  style={{ color: "#16C784" }}
                >
                  {value}
                </p>
                <p className="meta-label">{label}</p>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* ── 1. Product thesis ───────────────────────────────────────────── */}
      <div className="surface-card p-5 mb-6">
        <SectionHeader title="Why ClauseCompass exists" />
        <p className="text-[13px] leading-relaxed" style={{ color: "var(--cc-text-soft)" }}>
          Small in-house legal teams receive repetitive, low-risk commercial contracts that still
          require review. ClauseCompass explores how AI can reduce the repetitive first-pass triage
          burden while keeping legal judgment, redline approval, and final sign-off with humans.
          The workflow targets NDAs, order forms, vendor agreements, and boilerplate-heavy SaaS
          contracts — the contracts where most of the review time is spent verifying standard
          positions rather than making novel legal judgments.
        </p>
      </div>

      {/* ── 2. V1 → V2 evolution ────────────────────────────────────────── */}
      <div className="mb-6">
        <SectionHeader title="v1 → v2 evolution" />
        <div className="space-y-3">
          {TIMELINE.map((item, i) => (
            <div
              key={item.title}
              className="flex items-start gap-4 surface-card p-4"
              style={{
                borderLeft: "3px solid",
                borderLeftColor: i === 0 ? "rgba(22,199,132,0.25)" : "#16C784",
              }}
            >
              <div className="flex-shrink-0 pt-0.5">
                <span
                  className="pill"
                  style={{
                    background: i === 0 ? "rgba(143,163,174,0.1)" : "rgba(22,199,132,0.1)",
                    color: i === 0 ? "#566B76" : "#16C784",
                    border: `1px solid ${i === 0 ? "rgba(143,163,174,0.18)" : "rgba(22,199,132,0.2)"}`,
                    fontFamily: "monospace",
                    fontSize: 10,
                  }}
                >
                  {item.tag}
                </span>
              </div>
              <div className="flex-1 min-w-0">
                <p className="text-[13px] font-semibold mb-1" style={{ color: "var(--cc-text-muted)" }}>
                  {item.title}
                </p>
                <p className="text-[12px] leading-relaxed" style={{ color: "var(--cc-text-soft)" }}>
                  {item.desc}
                </p>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* ── 3. Engineering decisions ────────────────────────────────────── */}
      <div className="mb-6">
        <SectionHeader title="Engineering decisions" />
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {DECISIONS.map((d) => (
            <div key={d.title} className="surface-card p-4">
              <div className="flex items-center gap-2 mb-2">
                {d.icon}
                <p className="text-[13px] font-semibold" style={{ color: "var(--cc-text-muted)" }}>
                  {d.title}
                </p>
              </div>
              <p className="text-[12px] leading-relaxed" style={{ color: "var(--cc-text-soft)" }}>
                {d.desc}
              </p>
            </div>
          ))}
        </div>
      </div>

      {/* ── 4. Verification snapshot ────────────────────────────────────── */}
      <div className="mb-6">
        <SectionHeader title="Verification snapshot" />
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
          {METRICS.map((m) => (
            <div key={m.label} className="stat-card text-center" style={{ overflow: "hidden" }}>
              <p className="meta-label mb-2 relative z-10">{m.label}</p>
              <p
                className="text-[22px] font-bold leading-none mb-1 relative z-10"
                style={{ color: "#16C784" }}
              >
                {m.value}
              </p>
              <p className="text-[10px] relative z-10" style={{ color: "#364F5A" }}>{m.note}</p>
            </div>
          ))}
        </div>
      </div>

      {/* ── 5. Safety boundary ──────────────────────────────────────────── */}
      <div
        className="rounded-2xl p-4 mb-6 flex items-start gap-3"
        style={{ background: "rgba(239,68,68,0.04)", border: "1px solid rgba(239,68,68,0.14)" }}
      >
        <ShieldCheck size={14} color="#F56565" className="flex-shrink-0 mt-0.5" />
        <div>
          <p className="text-[12px] font-semibold mb-1" style={{ color: "#F87171" }}>Safety boundary</p>
          <p className="text-[12px] leading-relaxed" style={{ color: "#8FA3AE" }}>
            ClauseCompass is not legal advice and does not autonomously approve contracts. Outputs
            are prototype triage suggestions and require review against the full contract, legal
            playbook, and qualified legal judgment before external use.
          </p>
        </div>
      </div>

      {/* ── Bottom CTA ──────────────────────────────────────────────────── */}
      <div
        className="surface-card p-5 flex flex-col sm:flex-row sm:items-center justify-between gap-4"
      >
        <div>
          <p className="text-[13px] font-semibold mb-0.5" style={{ color: "var(--cc-text-muted)" }}>
            Interested in the workflow or the approach?
          </p>
          <p className="text-[12px]" style={{ color: "var(--cc-text-soft)" }}>
            Get in touch or explore the full codebase.
          </p>
        </div>
        <div className="flex flex-wrap gap-2">
          <CTAButton href={LINKS.email}       icon={<Mail size={13} />}         label="Email"     primary />
          <CTAButton href={LINKS.github}      icon={<Github size={13} />}       label="GitHub"    />
          <CTAButton href={LINKS.portfolio}   icon={<ExternalLink size={13} />} label="Portfolio" />
        </div>
      </div>

    </div>
  );
}
