import { PreflightStatus } from "../services/contractPreflight";

export interface PreflightTestCase {
  id: string;
  name: string;
  inputText: string;
  expectedStatus: PreflightStatus;
  rationale: string;
  category: "valid-contract" | "ambiguous-contract" | "non-contract" | "edge-case";
}

export const preflightTestCases: PreflightTestCase[] = [
  // ── Valid contracts ─────────────────────────────────────────────────────
  {
    id: "ptc-01",
    name: "Valid mutual NDA excerpt",
    category: "valid-contract",
    expectedStatus: "accept",
    rationale: "Standard mutual NDA with parties, confidentiality, governing law, termination, and signature block — should score well above accept threshold.",
    inputText: `MUTUAL NON-DISCLOSURE AGREEMENT

This Mutual Non-Disclosure Agreement ("Agreement") is entered into between ACME Limited ("Company") and Supplier Co Ltd ("Counterparty").

1. PURPOSE
The parties wish to explore a potential commercial relationship and may disclose confidential information to each other.

2. CONFIDENTIALITY
Each party shall hold the other's Confidential Information in strict confidence and shall not disclose it to any third party without prior written consent.

3. TERM AND SURVIVAL
This Agreement shall continue for two (2) years. The obligations of confidentiality shall survive termination for a further two (2) years.

4. LIABILITY
Each party's aggregate liability under this Agreement shall not exceed £10,000.

5. GOVERNING LAW
This Agreement is governed by the laws of England and Wales.

Signed: ______________________
Date: ______________________`,
  },
  {
    id: "ptc-02",
    name: "Valid SaaS order form",
    category: "valid-contract",
    expectedStatus: "accept",
    rationale: "SaaS order form with payment terms, liability, indemnity, auto-renewal, and governing law — multiple strong signals.",
    inputText: `CUSTOMER ORDER FORM

Order Reference: SOF-2024-00891

SUPPLIER: DataSoft Solutions Ltd ("Supplier")
CUSTOMER: ACME Limited ("Customer")

SERVICES: DataSoft Analytics Platform (Enterprise Tier)
Annual subscription fee: £48,000 per annum
Payment terms: Net 90 days from invoice date

AUTO-RENEWAL: This Order Form shall automatically renew for successive 12-month periods unless either party provides written notice of non-renewal at least 15 days prior to the end of the then-current subscription term.

INDEMNITY: Customer shall indemnify Supplier against all losses, damages, claims and expenses arising from Customer's use of the platform.

LIABILITY: Supplier's total liability shall not exceed £500. Customer's liability is unlimited.

GOVERNING LAW: This agreement is governed by the laws of England and Wales.

Signatures:
Supplier: ______________________
Customer: ______________________`,
  },
  {
    id: "ptc-03",
    name: "Valid enterprise MSA with high-risk clauses",
    category: "valid-contract",
    expectedStatus: "accept",
    rationale: "Full enterprise agreement with parties, defined terms, multiple clauses, and signature block.",
    inputText: `ENTERPRISE MASTER SUBSCRIPTION AGREEMENT

VENDOR: CloudBase Corporation ("CloudBase")
CUSTOMER: ACME Limited ("Customer")

Effective Date: As of execution

PAYMENT TERMS: All amounts are due and payable net ninety (90) days from invoice date.

LIABILITY: CloudBase's aggregate liability shall not exceed one hundred pounds sterling (£100). Customer's liability under this agreement is unlimited and shall survive termination indefinitely.

INDEMNIFICATION: Customer shall indemnify, defend, and hold harmless CloudBase from and against any and all claims, losses, damages, costs, and expenses arising from Customer's use of the platform. This indemnification is unlimited and irrevocable.

DATA PROCESSING: Customer grants CloudBase a perpetual licence to collect, process, analyse, and retain all data generated by Customer's use of the platform.

AUTO-RENEWAL: This agreement shall automatically renew for successive 36-month terms unless either party provides written notice at least 7 days prior to the end of the then-current term.

GOVERNING LAW: This agreement shall be governed by the laws of the State of Texas.

SIGNATURES:
CloudBase Corporation: ______________________
ACME Limited: ______________________`,
  },

  // ── Ambiguous contracts ─────────────────────────────────────────────────
  {
    id: "ptc-04",
    name: "Short contract-like NDA excerpt",
    category: "ambiguous-contract",
    expectedStatus: "warn",
    rationale: "Brief but clearly contract-like — has parties, confidentiality obligation, and governing law. Should warn (incomplete) but not reject.",
    inputText: `This Mutual NDA is entered into between Company and Supplier. The parties agree to keep confidential information secret for two years. Governing law is England and Wales.`,
  },
  {
    id: "ptc-05",
    name: "Partial agreement snippet with obligations",
    category: "ambiguous-contract",
    expectedStatus: "warn",
    rationale: "Has agreement language, parties, and shall obligations but is clearly an excerpt — should warn about completeness.",
    inputText: `This Agreement is entered into between the Licensor and the Licensee.

1. LICENCE GRANT
The Licensor hereby grants the Licensee a non-exclusive, non-transferable licence to use the Software.

2. RESTRICTIONS
The Licensee shall not sublicense, sell, or transfer the Software without prior written consent of the Licensor.

The Licensee covenants to keep all source code confidential.`,
  },
  {
    id: "ptc-06",
    name: "Invoice with some contractual language",
    category: "ambiguous-contract",
    expectedStatus: "warn",
    rationale: "Primary document is an invoice but includes payment terms and liability language that look contract-like — should warn, not accept or hard-reject.",
    inputText: `INVOICE NUMBER: INV-2024-00123
Bill to: ACME Limited
Payment due: 30 days from invoice date
Total amount due: £12,500

Payment terms: Net 30 days. Late payments shall incur interest at 8% per annum. Customer's liability for non-payment is unlimited. Governing law: England and Wales.`,
  },

  // ── Non-contracts ───────────────────────────────────────────────────────
  {
    id: "ptc-07",
    name: "CV / resume",
    category: "non-contract",
    expectedStatus: "reject",
    rationale: "Clear CV signals with work experience, education, and references — no contract language.",
    inputText: `CURRICULUM VITAE

Jane Smith
Software Engineer

Work Experience:
2021–Present: Senior Engineer, TechCorp Inc
- Led React and TypeScript front-end rebuild
- Designed AI workflow automation

Education:
BSc Computer Science, University of London, 2019

References available upon request.`,
  },
  {
    id: "ptc-08",
    name: "Job description",
    category: "non-contract",
    expectedStatus: "reject",
    rationale: "Job description with responsibilities and qualifications — no contractual structure.",
    inputText: `Job Description: AI Engineer

We are hiring an AI Engineer to join our growing legal technology team.

Key responsibilities:
- Design and implement prompt workflows
- Run stakeholder workshops on AI adoption
- Build evaluation pipelines for LLM outputs

Qualifications required:
- 3+ years engineering experience
- Experience with LLM frameworks
- Strong communication skills

About the role: This is a full-time position based in London.`,
  },
  {
    id: "ptc-09",
    name: "Meeting notes",
    category: "non-contract",
    expectedStatus: "reject",
    rationale: "Meeting notes with attendees, action items, and agenda — no contract structure.",
    inputText: `MEETING NOTES — Legal Ops Weekly

Date: 14 May 2026
Attendees: Sarah (Legal), Tom (Finance), Claire (Engineering)

Agenda:
1. Contract backlog review
2. Budget approval process

Action items:
- Sarah to follow up on NDA backlog by Friday
- Tom to confirm payment terms for Q3 vendor onboarding

Next steps: Claire to build intake dashboard by end of month.`,
  },
  {
    id: "ptc-10",
    name: "Blog article / marketing content",
    category: "non-contract",
    expectedStatus: "reject",
    rationale: "Blog post language with read more and subscribe signals — no contract structure.",
    inputText: `How AI is Transforming Legal Operations in 2026

In this article, we explore how legal teams are using AI to automate contract review. Read more about the top five use cases and how to get started.

Posted by: LegalTech Weekly
Published on: 12 May 2026

Subscribe to our newsletter for more insights. Follow us on LinkedIn and Twitter.

Comments (14)

Further reading: The future of legal AI, Automating contract workflows...`,
  },
  {
    id: "ptc-11",
    name: "Code / log output",
    category: "non-contract",
    expectedStatus: "reject",
    rationale: "Code snippet with function declarations and console.log — clearly not a legal document.",
    inputText: `import { useState } from "react";

const ReviewEngine = () => {
  const [status, setStatus] = useState(null);

  function runReview(contractText) {
    console.log("Running review...");
    const result = classify(contractText);
    setStatus(result);
  }

  return <div>{status}</div>;
};

export default ReviewEngine;`,
  },
  {
    id: "ptc-12",
    name: "Email thread",
    category: "non-contract",
    expectedStatus: "reject",
    rationale: "Email thread format with From/To/Subject headers — no contract structure.",
    inputText: `From: sarah@acme.com
To: tom@vendor.com
Subject: RE: NDA — follow up
Sent: 13 May 2026

Hi Tom,

Thanks for the follow up. I've reviewed the NDA draft and will send comments tomorrow.

Best,
Sarah

-----Original Message-----
From: tom@vendor.com wrote:
Hi Sarah, just checking on the NDA timeline. Can we sign by end of week?`,
  },
  {
    id: "ptc-13",
    name: "Very short / blank text",
    category: "edge-case",
    expectedStatus: "reject",
    rationale: "Too short to classify — below minimum character threshold.",
    inputText: `Hello this is a test.`,
  },
  {
    id: "ptc-14",
    name: "Short strong NDA — should not hard-reject",
    category: "edge-case",
    expectedStatus: "warn",
    rationale: "Very short but contains NDA keyword, parties, confidentiality, and governing law. Should warn not reject.",
    inputText: `NON-DISCLOSURE AGREEMENT between Company ("Disclosing Party") and Vendor ("Receiving Party"). The Receiving Party shall keep all Confidential Information secret. This Agreement is governed by the laws of England and Wales. Effective Date: 1 June 2026.`,
  },
  // ── Documentation / repository edge cases ──────────────────────────────
  {
    id: "ptc-16",
    name: "GitHub README / submission artefacts",
    category: "non-contract",
    expectedStatus: "reject",
    rationale: "Classic README structure with npm commands, docs folder references, and deployment platform — no party obligations. Should reject despite containing legal keywords like NDA and playbook.",
    inputText: `Submission artefacts
See the /docs folder:
- 01_README_START_HERE.md — Reviewer onboarding and review path
- 04_ARCHITECTURE_AND_DATA_FLOW.md — System design and data flow
- 06_EVAL_REPORT.md — Evaluation results and preflight pass rate

Run locally:
npm install
npm run dev

Deployment: Netlify
Tech stack: Vite, React, TypeScript, Supabase-ready architecture
Live demo: https://clausecompass.netlify.app
Video walkthrough: see /docs/03_LIVE_DEMO_AND_VIDEO_LINKS.md

Known limitations: No PDF parsing yet. NDA and order form samples only. Playbook is deterministic, not LLM-powered.`,
  },
  {
    id: "ptc-17",
    name: "Product documentation about a legal triage tool",
    category: "non-contract",
    expectedStatus: "reject",
    rationale: "Product description containing legal keywords (NDA, redline, liability, playbook) but no parties, obligations, or governing law. Should reject — this describes a product, not a contract.",
    inputText: `ClauseCompass is a first-pass legal triage tool for NDAs and order forms. It includes a deterministic playbook, an eval dashboard, redline suggestions, and a Supabase-ready architecture. The platform classifies contract risk as Green, Amber, or Red, and generates suggested redlines for liability, indemnity, governing law, and auto-renewal clauses. Built with Vite, React, and TypeScript. Powered by a rule-based review engine. Human approval required before any external redline is sent.`,
  },
  {
    id: "ptc-18",
    name: "Markdown-formatted contract with numbered clauses",
    category: "valid-contract",
    expectedStatus: "accept",
    rationale: "Real contract written in Markdown with parties, numbered clauses, obligations (shall), governing law, and effective date. Markdown formatting alone should not cause rejection.",
    inputText: `# Mutual Non-Disclosure Agreement

This Agreement is entered into between ACME Ltd ("Company") and Supplier Ltd ("Counterparty").

**Effective Date:** 1 June 2026

## 1. Confidentiality

Each party shall keep Confidential Information confidential and shall not disclose it to any third party without prior written consent of the other party.

## 2. Term

This Agreement commences on the Effective Date and continues for two (2) years. The obligations of confidentiality shall survive termination of this Agreement for a further two (2) years.

## 3. Liability

Each party's aggregate liability under this Agreement shall not exceed £10,000.

## 4. Governing Law

This Agreement is governed by the laws of England and Wales. The courts of England and Wales shall have exclusive jurisdiction.

Signed: ______________________
Date: ______________________`,
  },
  {
    id: "ptc-15",
    name: "Partner NDA with publicity and assignment clauses",
    category: "valid-contract",
    expectedStatus: "accept",
    rationale: "Full NDA with defined terms, confidentiality, assignment, publicity, governing law, and signature block.",
    inputText: `PARTNERSHIP NON-DISCLOSURE AND COLLABORATION AGREEMENT

This Agreement is entered into between MediaGroup plc ("MediaGroup") and ACME Limited ("ACME").

1. PURPOSE
The parties wish to explore a co-marketing and content partnership.

2. CONFIDENTIAL INFORMATION
"Confidential Information" means any non-public information disclosed by either party.

3. CONFIDENTIALITY OBLIGATIONS
Each party shall hold the other's Confidential Information in confidence and shall not disclose it to any third party.

4. PUBLICITY AND BRAND RIGHTS
MediaGroup shall have the right to use ACME's name and logo in marketing materials without prior approval from ACME.

5. ASSIGNMENT
MediaGroup may assign this Agreement to any MediaGroup group company without notice or consent from ACME.

6. TERM
This Agreement shall be in effect for one year from signing.

7. GOVERNING LAW
This Agreement is governed by the laws of England and Wales.

Signed: MediaGroup plc ______ ACME Limited ______`,
  },
];
