export const sampleEnterpriseOrderForm = `ENTERPRISE MASTER SUBSCRIPTION AGREEMENT — ORDER FORM

Order Reference: EMSA-2024-04471
Effective Date: As of execution

VENDOR: CloudBase Corporation, a Delaware corporation with principal offices at 500 Enterprise Parkway, Austin, Texas 78701 ("CloudBase")
CUSTOMER: ACME Limited, a company incorporated in England and Wales ("Customer")

SERVICES: CloudBase Enterprise Infrastructure Platform — Tier 1 contract
Annual contract value: £240,000
Contract term: 36 months from effective date

PAYMENT TERMS:
All amounts are due and payable net ninety (90) days from invoice date. CloudBase reserves the right to charge interest on overdue amounts at the rate of 18% per annum.

LIABILITY:
CloudBase's aggregate liability under this agreement shall not exceed one hundred pounds sterling (£100). Customer's liability under this agreement is unlimited and shall survive termination of the agreement indefinitely.

INDEMNIFICATION:
Customer shall indemnify, defend, and hold harmless CloudBase, its affiliates, officers, directors, agents, employees, and successors from and against any and all claims, losses, damages, costs, and expenses (including reasonable attorneys' fees) arising out of or relating to: (a) Customer's use of the platform; (b) any breach by Customer; (c) claims by Customer's end users; and (d) any claims by third parties arising from data processed through the platform. This indemnification is unlimited and irrevocable.

DATA PROCESSING:
Customer grants CloudBase a perpetual, worldwide, irrevocable licence to collect, process, analyse, retain, and commercialise all data generated by Customer's use of the platform, including for CloudBase's product development, benchmarking, machine learning training, and third-party analytics partnerships.

AUTO-RENEWAL:
This agreement shall automatically renew for successive 36-month terms unless either party provides written notice at least 7 days prior to the end of the then-current term.

SECURITY AUDIT RIGHTS:
Customer grants CloudBase and its designated third parties the right to conduct security audits of Customer's IT infrastructure, internal systems, and employee devices at any time with 2 hours' notice. Customer shall provide full access including to systems not directly related to the CloudBase platform.

GOVERNING LAW:
This agreement shall be governed by the laws of the State of Texas.

SIGNATURES:
CloudBase Corporation: ______________________
ACME Limited: ______________________`;

export const samplePartnerNDA = `PARTNERSHIP NON-DISCLOSURE AND COLLABORATION AGREEMENT

This Agreement is entered into between:

MediaGroup plc, a company incorporated in England and Wales (company number 04512789), with registered office at 88 Broadcast Lane, London, W1A 1AA ("MediaGroup"); and

ACME Limited, a company incorporated in England and Wales ("ACME").

1. PURPOSE
The parties wish to explore a potential co-marketing and content partnership. In connection with that exploration, each party may disclose confidential information to the other. This Agreement governs the use of that information.

2. CONFIDENTIAL INFORMATION
Confidential Information means any non-public information disclosed by either party, whether in writing, orally, or by any other means, that is designated as confidential or that a reasonable person would understand to be confidential.

3. CONFIDENTIALITY OBLIGATIONS
Each party shall hold the other's Confidential Information in confidence and shall not disclose it to any third party without prior written consent.

4. PUBLICITY AND BRAND RIGHTS
MediaGroup shall have the right to: (a) identify ACME as a MediaGroup partner in MediaGroup's marketing materials, pitch decks, and website; (b) use ACME's name, logo, and trade marks in any MediaGroup publication, press release, or investor communication; and (c) issue press releases announcing the partnership without prior approval from ACME. ACME acknowledges that MediaGroup operates in a time-sensitive media environment and that advance approval is not always practicable.

5. ASSIGNMENT
MediaGroup may assign this Agreement and all rights hereunder to any MediaGroup group company or to a purchaser of the MediaGroup business without notice to or consent from ACME.

6. TERM
This Agreement shall be in effect for one year from the date of signing. Upon expiry, all confidentiality obligations shall cease. The parties agree there is no need for obligations to survive beyond the contract period.

7. GOVERNING LAW
This Agreement is governed by the laws of England and Wales.

Signed:
MediaGroup plc: ______________________
ACME Limited: ______________________`;

export const sampleStandardNDA = `MUTUAL NON-DISCLOSURE AGREEMENT

This Mutual Non-Disclosure Agreement ("Agreement") is entered into as of the date last signed below between:

ACME Limited, a company incorporated in England and Wales (company number 01234567), whose registered office is at 1 King Street, London, EC2V 8AD ("Company"); and

Supplier Co Ltd, a company incorporated in England and Wales (company number 09876543) ("Counterparty").

1. PURPOSE
The parties wish to explore a potential commercial relationship and, in connection with that exploration, may disclose to each other certain confidential information. This Agreement sets out the terms on which such information will be shared.

2. DEFINITION OF CONFIDENTIAL INFORMATION
"Confidential Information" means any information disclosed by either party to the other, either directly or indirectly, in writing, orally or by inspection of tangible objects, that is designated as confidential or that reasonably should be understood to be confidential given the nature of the information and circumstances of disclosure.

3. OBLIGATIONS OF CONFIDENTIALITY
Each party agrees to: (a) hold the other party's Confidential Information in strict confidence; (b) not disclose such information to any third party without prior written consent; (c) use the Confidential Information solely for evaluating the potential commercial relationship; and (d) protect the Confidential Information using at least the same degree of care it uses to protect its own confidential information, but in no event less than reasonable care.

4. TERM AND SURVIVAL
This Agreement shall commence on the date of last signature and continue for a period of two (2) years. The obligations of confidentiality shall survive termination of this Agreement for a further period of two (2) years.

5. LIABILITY
Nothing in this Agreement limits either party's liability for fraud, wilful misconduct, or any other liability that cannot be excluded by law. Each party's aggregate liability under this Agreement shall not exceed £10,000.

6. GOVERNING LAW
This Agreement is governed by the laws of England and Wales. The courts of England and Wales shall have exclusive jurisdiction to settle any dispute arising out of or in connection with this Agreement.

7. ENTIRE AGREEMENT
This Agreement constitutes the entire agreement between the parties with respect to the subject matter hereof and supersedes all prior discussions and understandings.

Signed by the parties:

For and on behalf of ACME Limited:
Name: ______________________
Title: ______________________
Date: ______________________

For and on behalf of Supplier Co Ltd:
Name: ______________________
Title: ______________________
Date: ______________________`;

export const sampleRiskyNDA = `NON-DISCLOSURE AGREEMENT

This Non-Disclosure Agreement ("Agreement") is made as of this day between:

TechCorp Inc., a Delaware corporation with offices at 100 Market Street, San Francisco, California ("TechCorp"); and

ACME Limited ("Recipient").

1. CONFIDENTIAL INFORMATION
TechCorp may disclose Confidential Information to Recipient. Recipient agrees to keep all such information strictly confidential.

2. OBLIGATIONS
Recipient shall: hold all Confidential Information in strict confidence; not disclose to third parties; use only for purposes of evaluating a potential business relationship.

3. INDEMNIFICATION
Recipient shall indemnify, defend, and hold harmless TechCorp, its officers, directors, employees, agents, and successors from and against any and all claims, damages, losses, costs, and expenses (including reasonable attorneys' fees) arising out of or related to Recipient's breach of this Agreement or Recipient's use of TechCorp's Confidential Information. This indemnification obligation is unlimited and shall survive termination of this Agreement indefinitely.

4. LIABILITY
NOTWITHSTANDING ANY OTHER PROVISION OF THIS AGREEMENT, IN NO EVENT SHALL TECHCORP BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES. RECIPIENT'S LIABILITY UNDER THIS AGREEMENT SHALL BE UNLIMITED.

5. PUBLICITY
Recipient grants TechCorp the right to identify Recipient as a partner or customer and to use Recipient's name, logo, and trade marks in TechCorp's marketing materials, website, press releases, and investor presentations without further consent.

6. AUTO-RENEWAL
This Agreement shall automatically renew for successive one-year periods unless terminated by either party upon 14 days' written notice prior to the end of the then-current term.

7. ASSIGNMENT
TechCorp may assign this Agreement and its rights hereunder to any third party without consent or notice.

8. GOVERNING LAW
This Agreement shall be governed by and construed in accordance with the laws of the State of California, without regard to conflict of law principles.

9. SURVIVAL
Recipient's confidentiality obligations shall survive indefinitely.

Signed:
TechCorp Inc: ______________________
ACME Limited: ______________________`;

export const sampleOrderForm = `CUSTOMER ORDER FORM AND TERMS OF SERVICE

Order Reference: SOF-2024-00891
Date: As of order submission

SUPPLIER: DataSoft Solutions Ltd, 200 Tech Park, Manchester, M1 7PF ("Supplier")
CUSTOMER: ACME Limited, 1 King Street, London, EC2V 8AD ("Customer")

SERVICES ORDERED:
- DataSoft Analytics Platform (Enterprise Tier)
- Onboarding and implementation support
- Annual subscription

COMMERCIAL TERMS:
Annual subscription fee: £48,000 per annum
Payment terms: Net 90 days from invoice date

AUTO-RENEWAL:
This Order Form and the subscription shall automatically renew for successive 12-month periods unless either party provides written notice of non-renewal at least 15 days prior to the end of the then-current subscription term.

SECURITY AUDIT RIGHTS:
Customer agrees to grant Supplier the right to conduct periodic security assessments and audits of Customer's IT systems and infrastructure to verify compliance with Supplier's security standards. Such audits may be conducted at any time with 24 hours' notice.

DATA PROCESSING:
Customer grants Supplier a broad licence to collect, process, analyse, and store all data input into or generated by the platform, including for purposes of product improvement, benchmarking, and anonymised analytics. Supplier may share aggregated data with third parties.

INDEMNITY:
Customer shall indemnify Supplier against all losses, damages, claims and expenses arising from Customer's use of the platform, including claims by Customer's own end users.

LIABILITY:
Supplier's total liability shall not exceed £500. Customer's liability is unlimited.

GOVERNING LAW:
This agreement is governed by the laws of England and Wales.

SIGNATURES:
Supplier: ______________________
Customer: ______________________`;
